### ISSUE TITLE
Docker action error when using matrix strategy

### ISSUE THREAD

**Issue by michal-duda-sonarsource** [snyk/actions#10]
Snyk docker action doesn't work when GitHub action matrix strategy and `--project-name` are both used- I get the following error: `The following option combination is not currently supported: multiple paths + project-name`. Minimal reproducer:
```
name: CI

on: [push]

jobs:
  snyk-check:
    strategy:
      matrix:
        version: [7.9-community, 8.2-community]
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk for ${{ matrix.version }}
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        with:
          image: "sonarqube:${{ matrix.version }}"
          command: monitor
          args: --project-name="SonarQube Docker ${{ matrix.version }}"
```
