### ISSUE TITLE
Upload snyk test result to org UI

### ISSUE THREAD

**Issue by benj-fletch** [snyk/actions#12]
I would really like to be able to upload the results of a `snyk test` to the Snyk UI for our organisation. The situation I am trying to do this in is as follows:
### Repository
```
- .github
  -- \ workflow
        -- \ snyk-scan.yaml
- custom-image
  -- \ Dockerfile
```
I would then like to be able to run the equivalent of:
```
$ snyk auth $SNYK_TOKEN
$ snyk test --org=xyz
```
where the results of that test would be uplaoded under the organisation specified.

Ideally the SNYK token can be sourced from a GH actions secret. This should then not appear in any of the logs that are output from the GH action

**Comment by garethr** [comment]
The CLI command `snyk monitor` achieves what you want I think, sending the information to the Snyk UI. You can use than with the `command` property. If you'd like to pass an explicit org you can do so too, in `args`. Something like the following should work. Here you set both the API token and the Org ID as secrets in GitHub.

```yaml
name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        SNYK_ORG: ${{ secrets.SNYK_ORG }}
      with:
        command: monitor
        args: --org=${SNYK_ORG}
```
