### ISSUE TITLE
Produce full snyk test report but only fail action on specific severity

### ISSUE THREAD

**Issue by benj-fletch** [snyk/actions#13]
Since actions are often used for checks it would be really nice to be able to run a full `snyk test` in a repository and upload that to an organisation's page but also not fail the check unless vulns are found at a specific severity or higher. It might look something like the following.

#### Vulnerabilities in repo
1 low, 1 medium, 0 high.

#### Current Behaviour
```
jobs:
  full-snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ubuntu:latest
          args: --file=path/to/dockerfile --org=benj-fletch
```
This is the default run and will fail the `test` action since we have not specified otherwise.

#### Suggested behaviour
```
jobs:
  full-snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ubuntu:latest
          args: --file=path/to/dockerfile --org=benj-fletch
          failure-severity: high
```
This is a modified run and will not fail in this repo as there are no `high` vulnerabilities present

Thanks!
