### ISSUE TITLE
Python Action can't find Pip dependencies

### ISSUE THREAD

**Issue by klauern** [snyk/actions#15]
I am attempting to run the Snyk Python action but am having issues with it resolving the dependencies I install.  We are using self-hosted runners, but we are also limited in running only our own organization actions, so we have a process to mirror 3rd party repositories locally.  Here's what I have for a workflow:

```yaml
...
      - name: Checkout
        uses: <ourorg>/checkout@master
      - name: setup python
        uses: <ourorg>/setup-python@v2
      - uses: <ourorg>/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install Python dependencies
        run: |
          pip install -r ./requirements/requirements.txt
      - name: Run Snyk to check for vulnerabilities
        uses: <ourorg>/snyk_actions/python@master
        with:
          command: test
          args: --file=requirements/requirements.txt --package-manager=pip
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

```

However, when I run this, it still fails:

![CleanShot 2020-06-01 at 10 48 18@2x](https://user-images.githubusercontent.com/4735/83426948-94fac980-a3f5-11ea-935f-51371efb5b8e.png)

**Comment by garethr** [comment]
Apologies for talking a while to respond. My suspicion here is the Action is trying to access some private dependencies.
If this is still a problem, given you are already installing the packages, you could try the new [`setup`](https://github.com/snyk/actions/tree/master/setup) action instead and use the already installed packages.

Please do reopen this issue if that doesn't work.

**Comment by iannuzzelli** [comment]
I have the same problem, indeed it seems that the action cannot access the dependencies previously installed 

```
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: snyk/actions/setup@master
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: --org=${{ secrets.SNYK_ORG }}
```

It loads requirements.txt, but fails with "Required packages missing"

The only workaround I could think of is to avoid the use of Snyk actions and instead to manually install snyk via npm

```
  snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - name: Install Snyk
      run: |
        sudo apt install -y npm
        sudo npm install -g snyk
        snyk auth ${{ secrets.SNYK_TOKEN }}
    - name: Run Snyk to check for vulnerabilities
      continue-on-error: true
      run: |
        snyk monitor --org=${{ secrets.SNYK_ORG }}
```

**Comment by garethr** [comment]
I think this is probably private dependencies. The best bet is the setup action, which should be faster and get you the latest version of Snyk installed with a single line.

```yaml
 snyk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install -r requirements.txt
    - uses: snyk/actions/setup@master
    - name: Run Snyk to check for vulnerabilities
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: |
        snyk monitor --org=${{ secrets.SNYK_ORG }}
```
