### ISSUE TITLE
Internal error node project

### ISSUE THREAD

**Issue by Gmora08** [snyk/actions#16]
Hello I'm trying to run the snyk node action but throws an internal error
![image](https://user-images.githubusercontent.com/2798311/83919812-095ca200-a741-11ea-86d9-8e664c7e4bd1.png)

This is my .yml file

```
name: Code vulnerabilities with synk
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
```
