### ISSUE TITLE
Docker: action does not honor a snyk ignore'd vulnerabilty

### ISSUE THREAD

**Issue by Maciek416** [snyk/actions#17]
When I generate an ignore rule with `snyk ignore`, the resulting `.snyk` file doesn't seem to be honored by the github action (or `snyk test`). That is to say, the action fails because the scan fails.

I've made a test case for this (the result is the same for the CLI):

https://github.com/Maciek416/snyk-test-case/blob/master/Dockerfile
https://github.com/Maciek416/snyk-test-case/blob/master/.snyk

I invoke the action with the following yaml:

```yaml
      - name: Check docker image for vulnerabilities with Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: apiserver:push_candidate
          args: --file=apiserver/apiserver.Dockerfile --exclude-base-image-vulns
```

I've tried locating the `.snyk` file both in the root of my repository and in the `apiserver/` directory mentioned by the `--file` argument above. In both cases, the vulnerability `SNYK-ALPINE38-PROCPS-309362` is flagged and fails the scan.

Does the action (or perhaps CLI) not support applying ignore rules to docker yet?

**Comment by garethr** [comment]
For container projects you currently need to explicitly pass the policy file, using the `--policy-path` argument. If you could give that a try and see if that works for you?

**Comment by Maciek416** [comment]
Hey @garethr , I've tried the following and am not sure this argument is being used (or if it is, incorrect/bozo values seem to work too):

Variants with the assumption that the filename must be included in the arg:

- A1 `--policy-path=/home/runner/work/projectname/projectname/.snyk` - This is the `pwd` of repo root when in a GHA worker. This is also the docker build context of the Dockerfile. A `.snyk` file is placed here. (No effect on results)
- A2 `--policy-path=/home/runner/work/projectname/projectname/dockerfiledir/.snyk` - `.snyk` file placed in the same directory as the `Dockerfile`, just in case the policy file needs to be adjacent to the `Dockerfile` being scanned. (No effect on results)
- A3 `--policy-path=/directory/that/does/not/exist/.snyk` - To check if an obviously-incorrect path to the file causes an error. (No effect on results, no error related to file path either)

Variants with the assumption that its a path _to_ `.snyk`, but not a full path to the file itself.

- B1 `--policy-path=/home/runner/work/projectname/projectname` - like case A1, but without mentioning `.snyk`. (No effect on results)
- B2 `--policy-path=/home/runner/work/projectname/projectname/dockerfiledir` - like case A2, but without mentioning `.snyk` in the arg value. (No effect on results)

In all cases, I do see the policy argument appearing after `/usr/bin/docker run --name snyksnykdocker_0b9d74`, so the arg is being passed, but I'm not sure it's being consumed (mostly due to the result of A3).

Any ideas?

**Comment by mladkau** [comment]
Hello @Maciek416,

I've copied your sny-test-case repo and added an example GH Actions definition:

https://github.com/mladkau/snyk-test-case

In my [definition file](https://github.com/mladkau/snyk-test-case/blob/master/.github/workflows/action.yml) I added the `policy-path` argument and the action did work for me.

![image](https://user-images.githubusercontent.com/49239888/87945470-ae84cd00-ca98-11ea-8c5d-5abfacd40873.png)

Please note that the Action runs a Docker container inside the virtual environment of the GH Action so the path of the `policy-path` argument must be the path INSIDE the running Docker container! See also the manual steps in the README of my  version of the sny-test-case repo.

A GH Action like the following should work:
```
name: My GH Action
on: 
...
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
...
    - name: snyk-test
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: mladkau/snyk-test-case:latest
        args: --file=Dockerfile --exclude-base-image-vulns --policy-path=.snyk
```
