### ISSUE TITLE
gradle-jdk11 - project location changes in GHA

### ISSUE THREAD

**Issue by jeffalder** [snyk/actions#21]
## Steps:

1. Create new repo with `repo-name` as the repository.
2. Clone repo in the directory `repo-name`. 
3. Create one license issue.
4. Run `snyk monitor`.
5. Ignore license issue
6. Set up gradle-jdk11 GH Action.

## Expected result:

The ignored license issue doesn't fail `snyk test`.

## Actual result:

The ignored license issue fails `snyk test`.

## Why

The project file generated for the original `snyk monitor` call uses the directory name locally, `repo-name`, so the gradle script is registered as `repo-name/build.gradle.kts`.

When the GHA runs, it tests a file `workspace/build.gradle.kts`. Since this is seen as a different file by Snyk, the ignored dependency doesn't apply.

*How do I configure the GHA so that it realizes the `workspace` file is the same as the one under `repo-name`?*

**Comment by garethr** [comment]
Ah, interesting.

Could you try and pass the project name explicit and see if that works around the issue?

```yaml
name: Example workflow for Gradle using Snyk 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --project-name=repo-name/build.gradle.kts
```
