### ISSUE TITLE
Extend Github Code Scanning support

### ISSUE THREAD

**Issue by tpetry** [snyk/actions#30]
Currently on the docker and terraform snyk action do support uploading security vulnerabilities to the github security tab. It would be great to extend this functionality to all language actions.

**Comment by orfattal** [comment]
Hey @tpetry,

Reaching out to let you know that we now have an integral SARIF support in the CLI for Snyk Open Source.
It's still not part of the templates but you can easily try it out by using the syntax described in the sample action below: 
```
name: "Upload SARIF"
# Run workflow each time code is pushed to your repository.
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        args: --sarif-file-output=snyk-sarif.json
        continue-on-error: true        
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}     
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk-sarif.json
```


Happy to hear your feedback 🙏
