### ISSUE TITLE
Language specific actions should choose correct package management file

### ISSUE THREAD

**Issue by tpetry** [snyk/actions#31]
For frameworks like laravel the root directory will contain a npm and composer lock file. So a typical configuration may look like this:
```yaml
name: Scan for Vulnerabilities
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities (PHP)
        uses: snyk/actions/php@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities (JavaScript)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```

But the snyk action chooses for every action the `package-lock.json` which means the php action is doing the same as the node action. But the expectation is that a php action will run the logic on the `composer.lock` file. All actions should be extended to only use the package management files of their languages.

---

For the moment the code must be changed like this (for anyone having the same error):
```yaml
name: Scan for Vulnerabilities
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities (PHP)
        uses: snyk/actions/php@master
        with:
          args: --file=composer.lock
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities (JavaScript)
        uses: snyk/actions/node@master
        with:
          args: --file=package-lock.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```
