### ISSUE TITLE
Unhelpful 404 message on running the Docker action

### ISSUE THREAD

**Issue by rajbos** [snyk/actions#38]
See Action run [here](https://github.com/rajbos/dependency-updates/runs/1677777962?check_suite_focus=true)
Workflow file [here](https://github.com/rajbos/dependency-updates/blob/test/.github/workflows/pipeline.yml)

Action linked as per the docs [here](https://github.com/snyk/actions/tree/master/docker):
```
 - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: Dockerfile 
```
Dockerfile is in repo root.

**Issue**: error in logfile with message '404 page not found'. No idea what I did wrong.
