### ISSUE TITLE
Passing a command input suppresses all output

### ISSUE THREAD

**Issue by ripecosta** [snyk/actions#43]
Hello.

I am trying to run snyk as a GitHub Action and setting the `command` input to 'test' or 'monitor' depending on which branch it's running on. I've noticed that whenever a `command` input is set, there's no output.

Simplest example I could replicate:
```
name: Snyk

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  workflow_dispatch:
  
jobs:
  security:
    runs-on: ubuntu-latest
    env:
      COMMAND: test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=the-guardian-cuu --project-name=guardian/manage-frontend --file=./app/yarn.lock
          command: test
```
(the same happens if the command is 'monitor')

Result:
![image](https://user-images.githubusercontent.com/48949546/109858798-2d0f3300-7c54-11eb-9c04-3cff2fdfffe7.png)

Expected result: That the usual output would be shown, same as when a `command` input isn't set (and it default to test) or when running 'snyk test' locally.

For context, here is the code I was trying to implement when I detected this:
```
name: Snyk

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      COMMAND: test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set command to monitor
        if: github.ref == 'refs/heads/main'
        run: echo "COMMAND=monitor" >> $GITHUB_ENV

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=the-guardian-cuu --project-name=guardian/manage-frontend --file=./app/yarn.lock
          command: ${{ env.COMMAND }}
```

Thank you for your help.
