### ISSUE TITLE
Setting an env variable named 'command' causes snyk action to have no output

### ISSUE THREAD

**Issue by ripecosta** [snyk/actions#44]
Hello. As I have used the Snyk Node GitHub Actions I have noticed that setting an environment variable named `command` will cause the snyk action to have no output. [GitHub Action docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith) state that anything pass using `with` is set as an environment variable with an 'INPUT_' suffix I did not expect the presence of such variable to alter/break the behaviour of the action.

Code:
```
name: Snyk

on:
  schedule:
    - cron: "0 6 * * *"
  push:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    env:
      COMMAND: test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=the-guardian-cuu --project-name=guardian/manage-frontend --file=./app/yarn.lock
```

Output when setting `COMMAND` to 'test':
![image](https://user-images.githubusercontent.com/48949546/109989786-bb40f300-7d00-11eb-96da-644821292d43.png)

Output when setting `COMMAND` to 'monitor':
![image](https://user-images.githubusercontent.com/48949546/109989960-e0356600-7d00-11eb-8d34-08ea8a6c72cf.png)

Output when setting `COMMAND` to 'something-else':
![image](https://user-images.githubusercontent.com/48949546/109990038-f2af9f80-7d00-11eb-9928-fa1d4077ff45.png)
