### ISSUE TITLE
Upload result to GitHub Code Scanning for arm64v8 based image failed

### ISSUE THREAD

**Issue by martinussuherman** [snyk/actions#46]
Dear snyk, 
I've got problem when using this action for arm64v8 based image. 
The repository is here: https://github.com/martinussuherman/alpine

Related workflow run log:

Steps: Build Docker image using buildx
```
Run docker buildx build -t martinussuherman/alpine:glibc-arm64v8 -f glibc-arm64v8/Dockerfile .
time="2021-03-29T10:53:28Z" level=warning msg="No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load"
#1 [internal] load build definition from Dockerfile
#1 sha256:d3fde09c4d44be053419028fb6640b617ce183e2c2b6c94b33389d651111bdfd
#1 transferring dockerfile: 1.12kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:b0be8decf93f0fbeaadcec36053b0f28271332cddb42b3b49d5226b203111b82
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for docker.io/martinussuherman/alpine-glibc:arm64v8
#3 sha256:5db398a76974d1bac70028f3ccf2b1f25ba0b8b8ea6aab90da5de1d00d457b69
#3 ...

#4 [auth] martinussuherman/alpine-glibc:pull token for registry-1.docker.io
#4 sha256:0c3a689b544804eb8557c27a4851b987eefb180fbdc2b4b8c56ab7b82dcb355c
#4 DONE 0.0s

#3 [internal] load metadata for docker.io/martinussuherman/alpine-glibc:arm64v8
#3 sha256:5db398a76974d1bac70028f3ccf2b1f25ba0b8b8ea6aab90da5de1d00d457b69
#3 DONE 0.6s

#7 [internal] load build context
#7 sha256:5caa1eeda4823e9c999d59fe72c700b858cee5b4c744395d22b29274f6339210
#7 transferring context: 3.78kB done
#7 DONE 0.0s

#5 [1/4] FROM docker.io/martinussuherman/alpine-glibc:arm64v8@sha256:b710f6abb7d326422097e00228025b10f2c7f26630e4c4b3c9719a4e6bb58b1d
#5 sha256:13e47e8b7648726659a9be877cdbff584478ca62c05b7a825c043d68257d51ed
#5 resolve docker.io/martinussuherman/alpine-glibc:arm64v8@sha256:b710f6abb7d326422097e00228025b10f2c7f26630e4c4b3c9719a4e6bb58b1d done
#5 sha256:dce8679b510e95d136241d02ababff86469dd14220812a7ce9202833c0e32f66 2.71MB / 2.71MB 0.1s done
#5 extracting sha256:dce8679b510e95d136241d02ababff86469dd14220812a7ce9202833c0e32f66 0.1s done
#5 sha256:f0c6799797d4e114bdf2c421354dc86b2f200f9eda7ba002041fdb6104080e14 0B / 4.43MB 0.2s
#5 sha256:f0c6799797d4e114bdf2c421354dc86b2f200f9eda7ba002041fdb6104080e14 1.05MB / 4.43MB 0.6s
#5 sha256:f0c6799797d4e114bdf2c421354dc86b2f200f9eda7ba002041fdb6104080e14 3.15MB / 4.43MB 0.8s
#5 sha256:f0c6799797d4e114bdf2c421354dc86b2f200f9eda7ba002041fdb6104080e14 4.43MB / 4.43MB 0.8s done
#5 extracting sha256:f0c6799797d4e114bdf2c421354dc86b2f200f9eda7ba002041fdb6104080e14
#5 extracting sha256:f0c6799797d4e114bdf2c421354dc86b2f200f9eda7ba002041fdb6104080e14 0.1s done
#5 DONE 0.9s

#6 [2/4] RUN    apk --no-cache --update add    shadow    su-exec    tzdata
#6 sha256:5d410c117a2a2c1646d13427472586a80a2abf6fcd143bd64c53b2704bde1d37
#6 0.133 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
#6 0.357 fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
#6 0.883 (1/4) Installing linux-pam (1.3.1-r4)
#6 0.917 (2/4) Installing shadow (4.8.1-r0)
#6 0.967 (3/4) Installing su-exec (0.2-r1)
#6 0.974 (4/4) Installing tzdata (2021a-r0)
#6 1.132 Executing busybox-1.31.1-r19.trigger
#6 1.175 Executing glibc-bin-2.32-r0.trigger
#6 1.219 /usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-aarch64.so.1 is not a symbolic link
#6 1.220 
#6 1.236 OK: 20 MiB in 21 packages
#6 DONE 1.6s

#8 [3/4] COPY    chown-path    set-user-group-home    entrypoint-crond    entrypoint-exec    entrypoint-su-exec    /usr/bin/
#8 sha256:900000cc747582b743bda81414277cee1300ed2f34b9a0f6a1e793c4acc86add
#8 DONE 0.0s

#9 [4/4] RUN    chmod +x    /usr/bin/chown-path    /usr/bin/set-user-group-home    /usr/bin/entrypoint-crond    /usr/bin/entrypoint-exec    /usr/bin/entrypoint-su-exec
#9 sha256:eb90c7e04f96ec33929bf044d20c92058184e97068bd53225f20a513e68c74f7
#9 DONE 0.1s
```

Steps: Run Snyk to check Docker image for vulnerabilities
```
Run snyk/actions/docker@master
  with:
    image: martinussuherman/alpine:glibc-arm64v8
    args: --file=glibc-arm64v8/Dockerfile
    command: test
    json: false
    sarif: true
  env:
    SNYK_TOKEN: ***
/usr/bin/docker run --name snyksnykdocker_451f9b --label 5588e4 --workdir /github/workspace --rm -e SNYK_TOKEN -e INPUT_IMAGE -e INPUT_ARGS -e INPUT_COMMAND -e INPUT_JSON -e INPUT_SARIF -e SNYK_INTEGRATION_NAME -e SNYK_INTEGRATION_VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/alpine/alpine":"/github/workspace" snyk/snyk:docker  "snyk" "test" "--file=glibc-arm64v8/Dockerfile" "--docker" "martinussuherman/alpine:glibc-arm64v8"
manifest unknown

```

Steps: Upload result to GitHub Code Scanning
```
Run github/codeql-action/upload-sarif@v1
  with:
    sarif_file: snyk.sarif
    checkout_path: /home/runner/work/alpine/alpine
    token: ***
    matrix: null
Error: Path does not exist: snyk.sarif
Error: Path does not exist: snyk.sarif
    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:103:15)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:91:30)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:34:46)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:46:9)
```

Please help to resolve this problem. Thank you in advance.

Regards,

Martinus
