### ISSUE TITLE
Snyk Support for Lambda Function (Directory Perspective) 

### ISSUE THREAD

**Issue by NickLiffen** [snyk/actions#52]
Hello 👋 

We have a repository that is full of Python, Go & javascript functions. The high-level structure is:

```
- functions
  - function1
    - package.json
    - package-lock.json
 - function2
   - requirements.txt
 - function3
   - go.mod 
- template.yml
- README.md
```

I have a high-level GitHub Actions Workflow file that looks like this

```
python:
    strategy:
      fail-fast: false
      matrix:
        directory:
          - "./functions/pythonFunctionOne"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --dev --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

node:
    strategy:
      fail-fast: false
      matrix:
        directory:
          - "./functions/nodeFunctionOne"
          - "./functions/nodeFunctionTwo"
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    needs: [setup]
    name: JavaSript Testing
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Open Source Dependency Security Check
        uses: snyk/actions/node@0.3.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --dev --sarif-file-output=snyk.sarif
          command: test

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif


There is another `go` example but looks like the above ... 
```

However, I am getting the error message:

```
Could not detect supported target files in /github/workspace.
Please see our documentation for supported languages and target files: https://support.snyk.io/hc/en-us/articles/360000911957-Language-support and make sure you are in the right directory.
```

I can 100% confirm the right files are there. It does look like Snyk isn't honouring the `matrix` which it's running out of: as if I look here:

```
Testing /github/workspace...
```

It's at the root of the workplace. I have done some digging around and I think I could hack a solution together, but is there a good way of doing this? I can't get it working properly and I don't know if it's something wrong with this action or a broader thing 🤔 Any assistance would be great 👍
