### ISSUE TITLE
Node Action fails with `snyk` requires an authenticated account. Please run `snyk auth` and try again.

### ISSUE THREAD

**Issue by codepunkt** [snyk/actions#58]
See: https://github.com/codepunkt/webpack-license-plugin/runs/2950773911?check_suite_focus=true

I have a freshly regenerated token that is stored in a GitHub secret, used via environment variable:
https://github.com/codepunkt/webpack-license-plugin/blob/master/.github/workflows/test.yml#L16-L19

**Comment by jahed-snyk** [comment]
It's possible you have whitespace issues with your SNYK_TOKEN or a typo in your secret name.

Reasoning:

"SNYK_TOKEN" is visible in this line.
https://github.com/codepunkt/webpack-license-plugin/runs/2950773911?check_suite_focus=true#step:4:6

However, notice how the code coverage secret is not visible at all, including the "token" key:
https://github.com/codepunkt/webpack-license-plugin/runs/2950774042?check_suite_focus=true#step:6:2

I would've thought given this behaviour that "SNYK_TOKEN" shouldn't be visible either if it was set correctly with a secret.

Can you confirm your setup is correct?

To troubleshoot, you can also try using a simple command like `run: npx snyk test` to confirm if it's an issue with the action itself.

**Comment by codepunkt** [comment]
Both are set correctly as secrets - the snyk action ran before with the same secret configuration.
However, I don't know when it stopped working. I also revoked and regenerated on snyk, just to be sure.

Running `npx snyk test` instead did not work either:
https://github.com/codepunkt/webpack-license-plugin/runs/3002549267?check_suite_focus=true

**Comment by invidian** [comment]
We're experiencing the same issue in https://github.com/newrelic/nri-kube-events/pull/55. Suddenly, security scans stopped working.

**Comment by jahed-snyk** [comment]
@codepunkt when you run `npx snyk test` you'll need to provide the `SNYK_TOKEN` as an `env`. https://github.com/codepunkt/webpack-license-plugin/actions/runs/1005651910/workflow#L18

```yaml
security:
  runs-on: ubuntu-latest
  steps:
  - name: Run Snyk to check for vulnerabilities
    run: npx snyk test --severity-threshold=high
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```

Can you try again with that change? It'll help isolate where the issue is coming from, and if it works, it should provide a working alternative for you while we look into this.

**Comment by codepunkt** [comment]
@jahed-snyk Thanks!
This is the result of the latest run.
https://github.com/codepunkt/webpack-license-plugin/runs/3013463915?check_suite_focus=true

**Comment by jahed-snyk** [comment]
@codepunkt Add a `- uses: actions/checkout@v2` step before running Snyk and it should work now.

```yaml
security:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Run Snyk to check for vulnerabilities
    run: npx snyk test --severity-threshold=high
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```

Feel free to use this as an alternative while we allocate some time to look into why it's not authenticating using the action.
