### ISSUE TITLE
Snyk for Maven fails with missing JAVA_HOME

### ISSUE THREAD

**Issue by kgunnerud** [snyk/actions#6]
Tried using snyk actions but fails on missing JAVA_HOME.

```
Run snyk/actions/maven@master
  with:
    command: monitor
    args: --severity-threshold=false --include-provided-dependencies=false
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/13.0.1/x64
    JAVA_HOME_13.0.1_x64: /opt/hostedtoolcache/jdk/13.0.1/x64
    SNYK_TOKEN: ***
/usr/bin/docker run --name snyksnykmaven_5a37c5 --label af96b4 --workdir /github/workspace --rm -e JAVA_HOME -e JAVA_HOME_13.0.1_x64 -e SNYK_TOKEN -e INPUT_COMMAND -e INPUT_ARGS -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/pdl/pdl":"/github/workspace" snyk/snyk:maven  "snyk" "monitor" "--severity-threshold=false --include-provided-dependencies=false"
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE
##[error]Docker run failed with exit code 1
```

Action is defined as:
```
name: Build Branch

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Depdendencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build
        run: mvn -B clean test --threads=4 --batch-mode --settings ./.mvn/settings.xml
      - name: Run Snyk to check for Maven vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --severity-threshold=false --include-provided-dependencies=false
      - name: Run Snyk to check Docker images for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: navikt/java:13
          args: --severity-threshold=false
```
