### ISSUE TITLE
Snyk docker action doesn't pull image

### ISSUE THREAD

**Issue by IvanovOleg** [snyk/actions#60]
Hello,
I've found an annoing issue with the snyk/actions/docker@master action. The image is stored in the github container registry and built in the previous job.
```
inspect:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Log in to the Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
      
      # - run: docker pull ${{ needs.build.outputs.tags }}

      - name: "Run Snyk Docker"
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ needs.build.outputs.tags }}
          args: --file=Dockerfile`
```
If I leave that code as is and run the job, I will get:
`/usr/bin/docker run --name snyksnykdocker_475417 --label 3bec5f --workdir /github/workspace --rm -e CONTAINER_REGISTRY -e SNYK_TOKEN -e INPUT_IMAGE -e INPUT_ARGS -e INPUT_COMMAND -e INPUT_JSON -e INPUT_SARIF -e SNYK_INTEGRATION_NAME -e SNYK_INTEGRATION_VERSION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_DEBUG -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/github-actions-demo/github-actions-demo":"/github/workspace" snyk/snyk:docker  "snyk" "test" "--file=Dockerfile" "--docker" "ghcr.io/***/github-actions-demo:pr-1"
Failed to scan image "ghcr.io/***/github-actions-demo:pr-1". Please make sure the image and/or repository exist, and that you are using the correct credentials.`
I've changed the actual owner name with "***". If I uncomment **- run: docker pull ${{ needs.build.outputs.tags }}**, snyk starts testing the image.
