### ISSUE TITLE
Multi-file support - Documentation needs to be updated

### ISSUE THREAD

**Issue by shaneschnell** [snyk/actions#74]
It seems like multi-file support is available if you specify a period like the example below.  Can you verify and update the documentation?

```
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Snyk Code Scan
        id: snykcheck
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: .
```

https://github.com/snyk/actions/blob/14818c4695ecc4045f33c9cee9e795a788711ca4/iac/README.md?plain=1#L30
