### ISSUE TITLE
[Docker] illegal option -- 

### ISSUE THREAD

**Issue by dpnl87** [snyk/actions#9]
When I try to test my Github Action workflow with [act](https://github.com/nektos/act) I get the following error.

```
[Docker Image CI/build] ⭐  Run Run Snyk to check Docker image for vulnerabilities
[Docker Image CI/build]   ☁  git clone 'https://github.com/snyk/actions' # ref=master
[Docker Image CI/build]   🐳  docker run image=snyk/snyk:docker entrypoint=[] cmd=["--severity-threshold=high"]
| /usr/local/bin/docker-entrypoint.sh: exec: line 57: illegal option --
[Docker Image CI/build]   ❌  Failure - Run Snyk to check Docker image for vulnerabilities
```

My Action looks as follows:
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Registry
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN

      - name: Building Docker Image
        run: docker build --build-arg HUGO_VERSION=$HUGO_VERSION --no-cache
          -t $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:$HUGO_VERSION-$GITHUB_RUN_ID
          -t $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:latest .

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
          image: $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:$HUGO_VERSION-$GITHUB_RUN_ID
```

When running local in Docker it works fine:
```
docker run --rm -it -e SNYK_TOKEN=<token> -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk test --severity-threshold=high --docker dpnl87/hugo-docker:latest
```

**Comment by garethr** [comment]
Mmm, could you try something for me. Could you add the command to the args as well. ie. swap in:

`args: "snyk test --docker $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:$HUGO_VERSION-$GITHUB_RUN_ID --severity-threshold=high"`

My guess is act is replacing the `args` rather than adding to them as it should, ie. https://github.com/snyk/actions/blob/master/docker/action.yml#L18-L23

This could be a change in GitHub Actions behaviour (have you tried on GitHub Actions as well? I see this working for https://github.com/garethr/snyky/blob/master/.github/workflows/snyk.yml#L27 at https://github.com/garethr/snyky/runs/476635241?check_suite_focus=true). This could also be a bug or at least behaviour difference in act unfortunately.

**Comment by dpnl87** [comment]
Thank you @garethr. This worked.

```yaml
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: "snyk test --docker $DOCKER_USERNAME/$CONTAINER_IMAGE_NAME:$HUGO_VERSION-$GITHUB_RUN_ID --severity-threshold=high"
```
