### ISSUE TITLE
IaC action fails with git: not found error

### ISSUE THREAD

**Issue by menzenski** [snyk/actions#91]
I am trying to get the Snyk IaC action working on a repository containing Terraform module definitions.

My action (have simplified the matrix options a bit, but this is representative) looks like:

```yaml
name: Security
on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory:
          - dev
    steps:
      - name: Run Snyk
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: environments/${{ matrix.directory }}/main.tf

```

Any attempt to run this fails with
```
/bin/sh: git: not found
We were unable to read file "environments/dev/main.tf" for scanning. Please ensure that it is readable.
```

The file is present in the expected location, and is readable. If I add a `- run: ls -al` step in the workflow, I get an expected response:
```
-rw-r--r-- 1 runner docker 1277 Apr 19 15:18 main.tf
```

I did pull the `snyk/snyk:alpine` Docker image and can confirm it does not have `git` installed, so maybe that's the issue?:
```
$ docker run --pull missing --rm -it snyk/snyk:alpine git --version
/usr/local/bin/docker-entrypoint.sh: exec: line 92: git: not found
```

Is there any workaround? Thanks!

**Comment by menzenski** [comment]
Hmm, I've now gotten it to work locally by mounting the `main.tf` file:

```shell
$ docker run -v /absolute/path/to/main.tf:/app/main.tf -e SNYK_TOKEN=***--pull missing --rm -it snyk/snyk:alpine snyk iac test /app/main.tf
Testing main.tf...

Infrastructure as code issues:

Organization:      ***
Type:              Terraform
Target file:       main.tf
Project name:      app
Open source:       no
Project path:      /app/main.tf

Tested main.tf for known issues, found 0 issues
```

**Comment by menzenski** [comment]
Ended up just installing `snyk` from npm instead. This seems to work fine:

```yaml
name: Security

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: dev
    defaults:
      run:
        working-directory: environments/${{ matrix.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Snyk
        run: |
          npm install snyk@latest -g
      - name: Run Snyk
        run: |
          snyk iac test ./
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
```
